name: Docker Push
description: Set Image Tags and Push Images to ECR
inputs:
  images:
    description: Images to be pushed. Image tags will be used as suffix.
    required: false
  image-repos:
    description: Image Repositories
    required: false
    deprecationMessage: THIS INPUT IS DEPRECATED. Use 'images' instead.
  image-tag:
    description: Custom Image Tag
    required: false
    default: commit-sha
runs:
  using: composite
  steps:
    - name: Set Kustomization Image Tags
      shell: bash
      run: |
        export IMAGE_TAG="$(make -Bsf ${{ github.action_path }}/Makefile IMAGE_TAG="${{ inputs.image-tag }}" image-tag)"
        export IMAGES="${{ inputs.images }}"
        export IMAGE_REPOS="${{ inputs.image-repos }}"
        if [[ ! -z "${IMAGES}" ]] && [[ ! -z "${IMAGE_REPOS}" ]]
        then
          echo '"images" and "image-repos" inputs are not allowed simultaneously. "image-repos" is deprecated. Use "images" instead'
        elif [[ -z "${IMAGES}" ]]
        then
          export IMAGES="${IMAGE_REPOS}"
        fi

        make -Bf ${{ github.action_path }}/Makefile docker-push
