name: Docker Push
description: Tags Docker Images and Pushes them to ECR
inputs:
  image-repos:
    description: Image Repositories
    required: true
  image-tag:
    description: Custom Image Tag
    required: false
    default: commit-sha
runs:
  using: composite
  steps:
    - name: Set Kustomization Image Tags
      shell: bash
      run: |
        export IMAGE_REPOS="${{ inputs.image-repos }}"
        export IMAGE_TAG_INPUT="${{ inputs.image-tag }}"
        export IMAGE_TAG=$(test "${IMAGE_TAG_INPUT}" = 'commit-sha' && git describe --always --dirty --exclude '*' || printf "%s" "${IMAGE_TAG_INPUT}")
        export IMAGE_REGISTRY="${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com"

        for IMAGE_REPO in ${IMAGE_REPOS}
        do
            echo "skopeo 'docker-daemon:${IMAGE_REPO}' 'docker://${IMAGE_REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}'"
        done | parallel --lb -k
